### ISSUE TITLE
请教一个css  悬浮面板的引用链接高亮背景色

### ISSUE THREAD

**Issue by luluciamk** [mustakshif/Asri#100]
如图，大大，请注意一下红圈处（不是红线处）
![image](https://github.com/user-attachments/assets/78294489-0b87-478f-8ee9-3c7a891770b5)
我想要的是积读的这种效果
![image](https://github.com/user-attachments/assets/81233c5a-660f-437c-be0a-5f0f14e2171a)
即，之前大大给我的CSS，我改的链接都是双链样式
我想要这个悬浮面板里面的这个引用链接添加一个背景色（而正文的引用链接，还是保持原样）——
所以这里不是修改双链样式，而是应该跟悬浮面板的高亮背景色有关
这个请帮忙写下单独设置，非常感谢❤。

**Comment by mustakshif** [comment]
```css
[data-light-theme=Asri] .block__popover .protyle-wysiwyg [data-node-id] span[data-type~=block-ref]:not(.av__celltext), 
[data-light-theme=Asri] .block__popover .protyle-wysiwyg [data-node-id] span[data-type~=file-annotation-ref], 
[data-dark-theme=Asri] .block__popover .protyle-wysiwyg [data-node-id] span[data-type~=block-ref]:not(.av__celltext), 
[data-dark-theme=Asri] .block__popover .protyle-wysiwyg [data-node-id] span[data-type~=file-annotation-ref] {
    background-size: 100%;
}
```
