### ISSUE TITLE
Option to Disable Fade/Blur Effect at Banner Bottom Area

### ISSUE THREAD

**Issue by UsmanTechJive** [mustakshif/Asri#102]
Hi, I have a small request. I would appreciate it if you could provide an option to disable the fade/blur effect at the bottom area of the banner. The current fade style looks great, and I definitely want to keep it as it is because it's dope, but I would also like the option to disable this effect when needed. I tried implementing this on my own with CSS, but nothing seems to work. An option to toggle this effect or a CSS snippet to disable it would be greatly appreciated.

Please find the attached image for reference.

![image](https://github.com/user-attachments/assets/a460667c-1837-4fba-808b-d4f33b975bd8)

**Comment by mustakshif** [comment]
Here's a snippet to disable these effects. 

```css
[data-light-theme=Asri] body:not(.body-asri--mobile) .protyle-background.without-icon .protyle-background__img,
[data-light-theme=Asri] body:not(.body-asri--mobile) .protyle-background .protyle-background__img:not(.fn__none),
[data-dark-theme=Asri] body:not(.body-asri--mobile) .protyle-background.without-icon .protyle-background__img,
[data-dark-theme=Asri] body:not(.body-asri--mobile) .protyle-background .protyle-background__img:not(.fn__none) {
    margin-bottom: 0
}

[data-light-theme=Asri] .protyle-background__img::after,
[data-dark-theme=Asri] .protyle-background__img::after {
    display: none
}

[data-light-theme=Asri] .protyle-background__img img,
[data-dark-theme=Asri] .protyle-background__img img {
    mask-image: unset
}
```
Regarding a toggle feature - I plan to develop a comprehensive plugin that will consolidate all theme-related style toggles (including these blur and fade-out effects). While I haven't had time to implement this yet, you can use this snippet as an interim solution until the plugin is ready.
