### ISSUE TITLE
数据库选项的标签显示不完全

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#104]
![image](https://github.com/user-attachments/assets/5cab6167-347e-42e1-b013-def3a795ff7f)
如图，左侧应该有2px左右被遮挡了
新的方形标签外框挺好看的

**Comment by mustakshif** [comment]
<img width="222" alt="截屏2024-10-22 22 55 11" src="https://github.com/user-attachments/assets/ef046d7b-f89b-4148-91ad-e9fad386e9ca">

我这里没有问题，你看下是不是其他 css 片段导致的

**Comment by 5kyfkr** [comment]
我试了新gszo工作空间也一样，没带任何插件和css
![image](https://github.com/user-attachments/assets/c8041e5c-be42-478b-809f-3d8023ba2c37)

**Comment by mustakshif** [comment]
行的，我去windows测试下

**Comment by 5kyfkr** [comment]
这是我现在的魔改css，把savor的大页签给抄过来了，大佬有兴趣可以试试，直接复制开启就行
![image](https://github.com/user-attachments/assets/cfed19bf-af28-4a9c-8e3b-816809c6d649)


```css
/* ————————————————————主题颜色———————————————————— */

:root[data-theme-mode=light] {
--b3-theme-on-background: rgb(20,20,20);/*0,0,0*/
--b3-theme-on-surface: rgb(100,106,112);/*60,60,60*/
--b3-theme-surface: rgb(225,225,225);/*235，235，235*/
--b3-theme-background: rgb(242,242,242);/*255,255,255*/
--b3-toolbar-blur-background: rgb(47,54,61);
}
:root[data-theme-mode=light] .body--mobile {
--b3-theme-background: #F2F2F2 !important;
--b3-theme-on-background: #141414 !important;
}
:root[data-theme-mode=dark] {
--b3-theme-on-background: rgb(245,231,215);/*222, 219, 211*/
--b3-theme-on-surface: rgb(167,171,173);/*rgb(174, 183, 176)229,233,240*/
--b3-theme-background: rgb( 51, 53, 50);/*31, 40, 50*/
--b3-theme-surface: rgb( 32, 34, 31);/*31, 40, 50*/
--b3-toolbar-blur-background: rgb(46, 58, 73);
--b3-protyle-inline-strong-color: #e8eaed;
}
:root[data-theme-mode=dark] .body--mobile {
--b3-theme-background: #3D3F3C !important;
--b3-theme-on-background: #F5E7D8 !important;
}


:root[data-theme-mode=light]{
#toolbar {
background-color:  rgb(225,225,225) !important;/*rgb(224,232,234)*/
}
.protyle-breadcrumb {
background-color: rgb(242,242,242) !important;
}
#dockLeft.dock.dock--vertical{
 background-color: rgb(225,225,225) !important;
}
#dockRight.dock.dock--vertical{
 background-color: rgb(225,225,225) !important;
}
.layout-tab-bar {
    z-index: 3;
}
body:not(.body--mobile, .body--window) .layout__dockl.layout--float::before {
    background-color: rgb(225,225,225);
}
.protyle-breadcrumb__text{
 font-size: 14px !important;
}
}

:root[data-theme-mode=dark]{
#toolbar {
background-color: rgb( 32, 34, 31) !important;
}
.protyle-breadcrumb {
background-color: rgb( 51, 53, 50) !important;
}
#dockLeft.dock.dock--vertical{
 background-color: rgb( 32, 34, 31) !important;
}
#dockRight.dock.dock--vertical{
 background-color: rgb( 32, 34, 31) !important;
}
.layout-tab-bar {
    z-index: 3;
}
body:not(.body--mobile, .body--window) .layout__dockl.layout--float::before {
    background-color: rgb( 32, 34, 31);
}
.protyle-breadcrumb__text{
 font-size: 14px !important;
 color: rgb(167,171,173);
}
}

/* 编辑区圆角 */
:root[data-theme-mode=light] .layout-tab-container {
    background-color: rgb(225,225,225);
}
:root[data-theme-mode=dark] .layout-tab-container {
    background-color: rgb( 32, 34, 31);
}
.protyle-breadcrumb {
    background-color: transparent;
}
.protyle {
    border-radius: 12px 12px 0 0;
}

/* ————————————————————Asri页签修改———————————————————— */
body:not(.body-asri--mobile,.body--window) .layout__center .layout-tab-bar {
    margin: 8px 8px 6px 4px !important;
}

/* ————————————————————页签1———————————————————— */
.layout-tab-bar{
	& .item{
		margin:0px;
		pointer-events: visibleFill;
		&[data-type="tab-header"]{
			pointer-events: visibleFill;
			app-region: no-drag;
			padding: 0 0px;
			min-height: 35px;
			border-radius: 3px 3px 0 0 !important;
                        background-color: transparent;
			&.item--focus{
			background-color: var(--b3-theme-background) ;
                        border-radius: 6px 6px 0 0 !important;
				&:
			after{
					display: none;
				}
				& .item__text{
			font-weight:700;
				}
			}
		}
	}
		& .item--readonly{
		padding: 0px;
		pointer-events: none;
		background-color:var(--S-toolbar-background);
		height: 38px;
		width: 70px;
		&>.fn__flex-1{
			display: none;
		}
		& .block__icon--show{
			pointer-events: visibleFill;
			app-region: no-drag;
			margin-left: 7px;
		}
	}	
}


/* ————————————————————页签———————————————————— */
.layout-tab-bar{
	height: 38px;
        border-radius: 0px !important;
	padding-left: 0px;
	& .item{
		border-radius: 0px !important;
		min-height:unset;
		min-width:unset;
		overflow:visible;
		height: 26px;
		margin:0 0px;
		& .item__text{
			padding: 2px 6px; 
			-webkit-mask-image:none;
		}
		& .item__close{
			padding: 4px 2px 4px 2px;
			svg{
				height: 12px;
				width: 12px;
			}
		}
		&.item.item--focus .item__close svg{
			opacity: 0;
		}
		&.item.item--focus:hover .item__close svg{
			opacity: 1;
		}
	}
	& .item:not(.item--readonly):hover{
		background-color:var(--S-list-background)!important;
	}
	& .item--readonly{
		margin:7px 0 0 7px;		
	}
}
.layout-tab-bar .item--focus:after{
	background-color: transparent;
	box-shadow: var(--b3-theme-background-light) 0px 6px 0px;
}
.layout__wnd--active .layout-tab-bar .item--focus::after{
	background-color: transparent;
	box-shadow: var(--S-item-focus) 0px 6px 0px;
}
body.body--blur .layout__wnd--active .layout-tab-bar .item--focus{
	box-shadow: none!important;
}
.layout-tab-bar .item--pin{
	& .item__icon{
		padding:0px 5px;
	}
	& .item__graphic{
		padding:4px;
	}
	&:nth-child(4n-3){
		background-color:transparent;
	}
	&:nth-child(4n-2){
		background-color:transparent;
	}
	&:nth-child(4n-1){
		background-color:transparent;
	}
	&:nth-child(4n){
		background-color:transparent;
	}
}

/*顶栏高度和对齐*/
.toolbar {
height: 40px !important;
border-bottom: 0.5px solid rgba(0,0,0,0);
}
.layout-tab-bar {
position: relative;
top: 3.5px;
}
#AsriPluginsIconsDivider  {
top: 10px !important;
background-color: rgba(180,180,180,0) !important;
}

/*侧栏宽度*/
.dock--vertical  {
 width:38px !important;
}
```
