### ISSUE TITLE
Enhancement Request: Dynamic Left Space Adjustment for Blocks with Background Color

### ISSUE THREAD

**Issue by UsmanTechJive** [mustakshif/Asri#110]
I think if the user hasn’t applied any background color, it looks fine. However, once a background color is applied, there should be space on the left to match the top, right, and bottom spaces, making the content look more balanced, and as soon as the background color is removed, the left space should also be removed to default as well. This would look much better. I believe this could be improved.

https://github.com/user-attachments/assets/2b321da5-845a-41a0-a5fb-54bf9402f582

This is what I mean once user apply background color, equal spaces on all sides. Make sure it also balance the super blocks as well.

![image](https://github.com/user-attachments/assets/7d4d6207-f433-4b8d-b503-1c1c82de6bf3)

Currently this is how super block looks like when I'm applying the background color...

![image](https://github.com/user-attachments/assets/edb2cbea-f796-49ec-a251-a99bd9b675fe)

**Comment by mustakshif** [comment]
I've also noticed that issue. My solution was to use a quote block with a custom background color as a workaround.

<img width="824" alt="image" src="https://github.com/user-attachments/assets/dc9091da-abb1-4560-82e0-566708676377">

**Comment by UsmanTechJive** [comment]
I was using your solution, but then I realized I prefer the quote block styled more like this...

![image](https://github.com/user-attachments/assets/6c57f395-e9c8-41d5-939e-0a8c45c2043f)

Then I added this custom CSS

```
/* Left Border Radius Fix */
.protyle-wysiwyg blockquote>p, .protyle-wysiwyg [data-node-id] {
    border-radius: 0px !important; /* var(--b3-border-radius) */
}

.protyle-wysiwyg [data-node-id].bq {
    border-radius: 0px !important;
}

/* Text Spacing */
.protyle-wysiwyg .bq>[data-type=NodeHeading], .protyle-wysiwyg blockquote>[data-type=NodeHeading], .protyle-wysiwyg .bq>[data-type=NodeParagraph], .protyle-wysiwyg blockquote>[data-type=NodeParagraph] {
    padding-left: 9px !important;
}

/* Border & Background Fix */
.protyle-wysiwyg .bq, .protyle-wysiwyg blockquote {
    border: 0px solid var(--b3-border-color-trans); /* 1.5 */
    background-color: transparent !important; /* var(--b3-theme-surface-light) */
}

/* General Style */
.b3-typography blockquote, .b3-typography .bq, .protyle-wysiwyg blockquote, .protyle-wysiwyg .bq {
    padding: 4px;
    color: var(--b3-theme-on-surface);
    border-left: .25em solid var(--b3-theme-surface-lighter) !important;
    background-color: var(--b3-bq-background);
    margin: 4px 0;
}
```

This is how it looks now:

![image](https://github.com/user-attachments/assets/2f6fe321-1c3a-4dd6-a9c6-849bd5c66815)

Because of my custom quote block style, I need a way to easily add a background color to a block or super block with nicely rounded corners and proper spacing on all sides—just like yours as using quote block. That’s why I asked if you could improve the left spacing issue when a background color is applied.

> <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/100056458/382008998-dc9091da-abb1-4560-82e0-566708676377.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODk4MzQsIm5iZiI6MTczMDM4OTUzNCwicGF0aCI6Ii8xMDAwNTY0NTgvMzgyMDA4OTk4LWRjOTA5MWRhLWFiYjEtNDU2MC04MmUwLTU2NjcwODY3NjM3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNTQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjA5NGQyNGFkZDUxZDE0YmIxNDYzNmJiNDU5MTI3ZDJiOTgyZmY5ZmUwNzY1NjFhYTNlNmFkNTJjMmE3YTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d_nJBVwtk8YOZ0bcD6YFNmrihpqbeCG9BVnp_karkNI">

**Comment by mustakshif** [comment]
I decided against adding this feature because it would require extensive use of [style*='background-color'] selectors, which could impact performance.

As an alternative, you can nest headings and content within a block quote to create colored blocks in your document flow. While this achieves a similar visual result, there is one limitation: headings inside block quotes won't appear in the outline panel.

If you still want to implement the original approach, here's a code snippet you can try:

```css
.protyle {
    [style*="background-color"]:is(.p, .list) {
        padding: 1em 1.2em;
    }

    .h1[style*=background-color] {
        padding: calc(1em / 1.75) calc(1.2em / 1.75);
    }
    .h2[style*=background-color] {
        padding: calc(1em / 1.55) calc(1.2em / 1.55);
    }
    .h3[style*=background-color] {
        padding: calc(1em / 1.38) calc(1.2em / 1.38);
    }
    .h4[style*=background-color] {
        padding: calc(1em / 1.25) calc(1.2em / 1.25);
    }
    .h5[style*=background-color] {
        padding: calc(1em / 1.13) calc(1.2em / 1.13);
    }
    .h6[style*=background-color] {
        padding: 1em 1.2em;
    }
}
```
