### ISSUE TITLE
Add Subtle Animation to Slash Menu Opening

### ISSUE THREAD

**Issue by UsmanTechJive** [mustakshif/Asri#128]
I have modified the slash (/) menu opening animation as shown in the video while I'm not certain about the current animation quality, perhaps you could enhance it further.

https://github.com/user-attachments/assets/a79d7ca9-85f7-4585-b84c-e75f5ed85f72

Here is my CSS snippet:

```
/* Opening Animation */
.protyle-hint {
    opacity: 0;
    transform-origin: top left;
    transform: scale(0.985);
    animation: scaleBounce 0.25s cubic-bezier(0.12, 0.95, 0.4, 1) forwards;
    will-change: transform, opacity;
    backface-visibility: hidden;
}

@keyframes scaleBounce {
    0% {
        opacity: 0;
        transform: scale(0.985);
    }
    70% {
        opacity: 1;
        transform: scale(1.002);
    }
    100% {
        opacity: 1;
        transform: scale(1);
    }
}

```

**Comment by UsmanTechJive** [comment]
I just noticed you removed the banner's bottom blur effect. Could you share the CSS code for this?

**Comment by mustakshif** [comment]
The animation looks smooth and natural! I'll integrate it into my code.

> I just noticed you removed the banner's bottom blur effect. Could you share the CSS code for this?

Check here (you can ignore the commented-out sections):

https://github.com/mustakshif/Asri/blob/576b524f8a3a4e9c6b95cf6cd19cc139ba7c42f7/styles/features/cover-image-fading.scss#L3-L41

**Comment by UsmanTechJive** [comment]
> The animation looks smooth and natural! I'll integrate it into my code.
> 
I'm glad to hear that.

> > I just noticed you removed the banner's bottom blur effect. Could you share the CSS code for this?
> 
> Check here (you can ignore the commented-out sections):
> 
> https://github.com/mustakshif/Asri/blob/576b524f8a3a4e9c6b95cf6cd19cc139ba7c42f7/styles/features/cover-image-fading.scss#L3-L61

Thanks! 🙏

**Comment by UsmanTechJive** [comment]
I've tried your code with all plugins and snippets disabled, but when I scroll up, the blur effect is not staying consistent. Any fix would be appreciated.

https://github.com/user-attachments/assets/ff4463d8-62b0-47a6-83c1-5790cc614fc7

**Comment by mustakshif** [comment]
Discard the previous snippet and try this one:

```css
.protyle-background__img {
    &::after {
        content: "";
        display: inline-block;
        width: -webkit-fill-available;
        height: 30vh;
        position: absolute;
        top: 0;
        right: 0;
        background: linear-gradient(to top, var(--b3-theme-background) 2%, rgba(from var(--b3-theme-background) r g b / .97) 9%, rgba(from var(--b3-theme-background) r g b / 0.9) 18%, rgba(from var(--b3-theme-background) r g b / .75) 33%, rgba(from var(--b3-theme-background) r g b /.05) 92%, transparent 99%);
        pointer-events: none;
    }
}
```
