### ISSUE TITLE
Add gradient fade effect to scrollable tabs edges

### ISSUE THREAD

**Issue by UsmanTechJive** [mustakshif/Asri#135]
What if we add a similar fade effect on both the left and right edges of the tabs when scrollable?

**Here's how it should work:**

- By default, don't show the fade effect on the left side
- Show the fade effect on the right side only when there are many tabs that require scrolling
- As soon as the user scrolls to the right, show the fade effect on the left side edge as well because its scroll-able
- When the user reaches the rightmost end of the tabs, hide the fade effect on the right side while maintaining it on the left side

Currently, tabs get cut off on edges, but adding a smooth gradient fade effect would create a more polished look imo.  What are your thoughts on this improvement?

### **Without Fade Effect:**

![image](https://github.com/user-attachments/assets/b761622e-d67f-4c5c-8a13-456c9421d9bf)

### **With Fade Effect:**
![image](https://github.com/user-attachments/assets/71b22a59-c5ba-4ddc-ac75-28bc0bbc340b)

Edit: I've just tested this, and while my implementation of the fade effect isn't perfect, I hope the concept is clear enough to understand for you.

**Comment by mustakshif** [comment]
I know what you mean.  Try this:

```css

.layout-tab-bar {
    -webkit-mask-image: linear-gradient(to right, transparent, black var(--mask-stop-start), black calc(100% - var(--mask-stop-end)), transparent);
    mask-image: linear-gradient(to right, transparent, black var(--mask-stop-start), black calc(100% - var(--mask-stop-end)), transparent);
    animation-name: maskAppear-mask-start-ujizgbo, maskAppear-mask-end-ujizgbo;
    animation-range: 1px 100%, 0% calc(100% - 1px);
    animation-direction: alternate, alternate-reverse;
    animation-timeline: scroll(self x)
}

@keyframes maskAppear-mask-start-ujizgbo {
    0% {
        --mask-stop-start: 0px
    }

    1% {
        --mask-stop-start: 18px
    }

    100% {
        --mask-stop-start: 18px
    }
}

@keyframes maskAppear-mask-end-ujizgbo {
    0% {
        --mask-stop-end: 0px
    }

    1% {
        --mask-stop-end: 18px
    }

    100% {
        --mask-stop-end: 18px
    }
}
```
