### ISSUE TITLE
样式优化——备注的弹窗界面比较刺眼

### ISSUE THREAD

**Issue by luluciamk** [mustakshif/Asri#141]
思源原生自带的“备注”在asri的主题下可以优化吗

 

备注的弹窗界面无法截图

目前，在夜间模式下，asri的这个备注，弹窗界面跳出来，是亮黄色背景+圆体较细文字

在较暗的地方看起来，和其他背景对比起来非常刺眼。
- 可否将这个备注弹窗的背景色与其他颜色修改为统一？黄色与黑色对比不够明显
- 可否将弹窗的内容字体调整得稍微大一点（还是说，这个有特定CSS，可以的话，请大大帮忙写一份调整asri主题下的这个弹窗字体大小的css）

**Comment by mustakshif** [comment]
> 备注的弹窗界面无法截图

这个能详述一下吗，我这边可以正常截图



> 目前，在夜间模式下，asri的这个备注，弹窗界面跳出来，是亮黄色背景+圆体较细文字

颜色问题下个版本优化。圆体字应该是你自己的代码片段弄的？我没有在主题中用圆体字

> * 可否将弹窗的内容字体调整得稍微大一点（还是说，这个有特定CSS，可以的话，请大大帮忙写一份调整asri主题下的这个弹窗字体大小的css）

```css
:where([data-light-theme="Asri"], [data-dark-theme="Asri"]) .tooltip--memo#tooltip {
    font-size: 18px;
}
```

**Comment by luluciamk** [comment]
收到。感谢大大回复。
这个字体，我感觉应该是思源自带（仔细看了看，它在弹窗界面设定的，就是这个很细的字体，再加上这个黄色界面，视觉上看起来相当艰难啊。）更改字体大小，应该可以改善。😃

**Comment by mustakshif** [comment]
如果觉得太细，也可以加粗的：
```css
:where([data-light-theme="Asri"], [data-dark-theme="Asri"]) .tooltip--memo#tooltip {
    font-size: 18px; /*这里自己改*/
    font-weight: bold;
}
```
