### ISSUE TITLE
一个问题和建议

### ISSUE THREAD

**Issue by z2023711** [mustakshif/Asri#143]
如图，v3.1.20版本的思源笔记以及最新版本的主题，设置界面出现了如下情况，

![Image](https://github.com/user-attachments/assets/6fc69b35-fcbb-4ac0-aa37-0d9e1bb64c79)
我选择默认主题后则没有这种状况，请问这是主题新的特性吗？还是说是bug？

我建议将标签修改成下图，固定标签的长度，少的标题全部显示出来，多的，则是隐藏一部分。这样看起来很整齐，

![Image](https://github.com/user-attachments/assets/3f48e5fe-f8e4-4580-bb29-8902ad448da8)

还有就是，我在想思源的编辑区的背景颜色的修改是否可以让整个界面更好看一些呢？

**Comment by mustakshif** [comment]
> 我选择默认主题后则没有这种状况，请问这是主题新的特性吗？还是说是bug？

是特性，避免一行中文字太多影响阅读

恢复可以使用以下 CSS 代码片段：

```css
[data-light-theme=Asri], [data-dark-theme=Asri] {
    .config__panel .config__tab-wrap .config__tab-container, .config__panel .config__tab-wrap .config__tab-container:where([data-name=AI],[data-name=image]) .layout-tab-bar+.fn__flex-1 {
        padding: 8px 12px;
    }
}
```

> 我建议将标签修改成下图，固定标签的长度，少的标题全部显示出来，多的，则是隐藏一部分。这样看起来很整齐，
> 
> ![Image](https://github.com/user-attachments/assets/3f48e5fe-f8e4-4580-bb29-8902ad448da8)

固定页签长度可以使用以下 CSS 代码片段：

```css

[data-light-theme=Asri], [data-dark-theme=Asri] {

    :not(.av__views)>.layout-tab-bar .item:not(.item--pin,.item--readonly) {
        min-width: 186px; /* 数值可自己调整，保持两个一致 */
    }
    .layout-tab-bar .item--focus {
        max-width: 186px; /* 数值可自己调整，保持两个一致 */
    }

    .layout-tab-bar .item:not(.item--pin, .item--focus) .item__text,
    .layout-tab-bar .item:not(.item--pin, .item--focus) .item__icon, .layout-tab-bar .item:not(.item--pin, .item--focus) .item__icon + .item__text {
        transform: none;
    }

    .layout-tab-bar .item__text { 
        flex-grow: 1;
        text-align: start;
    }

}
```



> 还有就是，我在想思源的编辑区的背景颜色的修改是否可以让整个界面更好看一些呢？

好看的标准每个人不一样，你有什么具体建议吗
