### ISSUE TITLE
希望能添加双链样式

### ISSUE THREAD

**Issue by bemofan** [mustakshif/Asri#146]
![Image](https://github.com/user-attachments/assets/c2ed0013-62df-408b-b49c-168a9c96dd90)
如图所示，动态锚文本使用[[包裹，静态使用[，可以自定义颜色。

特别希望去除默认下划线，真的很影响美感。

非常喜欢您的主题，祝好，望采纳！

**Comment by mustakshif** [comment]
感谢喜欢！去除下划线可以用下面的CSS代码片段：
```css
:where([data-light-theme=Asri], [data-dark-theme=Asri]) [data-node-id] span[data-type~=block-ref]:not(.av__celltext) {
    text-decoration: none !important;
}
```
