### ISSUE TITLE
KBD修改建议

### ISSUE THREAD

**Issue by HakunaMatata-Z** [mustakshif/Asri#157]
您好，

可否将KBD修改为类似下图的样式，去掉Box-shadow/background-image/text-shadow，方便阅读。

ps：我尝试自己更改CSS代码样式，但是删除以上元素后出现界面混乱的文图。

BR

![Image](https://github.com/user-attachments/assets/0bb224eb-5e08-4347-88b6-a7692283da04)

**Comment by mustakshif** [comment]
现在版本有不方便阅读的地方吗？如果文字不够突出，可以改颜色：

```css
[data-light-theme="Asri"],[data-dark-theme="Asri"] {
    :is(.b3-typography, .protyle-wysiwyg) :is(span[data-type~="kbd"], kbd) {
        color: inherit;
    }
}
```
