### ISSUE TITLE
bug: 特定字母会遮挡链接的下划线 | certain letters can obscure the underlines in links

### ISSUE THREAD

**Issue by RehemChan** [mustakshif/Asri#158]
如图所示，特定字母如“qypgj”可能遮挡部分链接的下划线，导致显示有点奇怪

![Image](https://github.com/user-attachments/assets/764d4e36-aaf1-47ae-a06d-39ebe89c9719)

**Comment by mustakshif** [comment]
我在 Windows 上测试了一下，当编辑器字体大小大于 18px 后会出现，调整窗口大小后会短暂恢复，可能是字体渲染的 bug。

可以添加自定义代码片段试试：
```css
[data-light-theme="Asri"],[data-dark-theme="Asri"] {
    body {
        text-underline-offset: .1em;
    }
}
```

**Comment by RehemChan** [comment]
> 我在 Windows 上测试了一下，当编辑器字体大小大于 18px 后会出现，调整窗口大小后会短暂恢复，可能是字体渲染的 bug。
> 
> 可以添加自定义代码片段试试：
> 
> [data-light-theme="Asri"],[data-dark-theme="Asri"] {
>     body {
>         text-underline-offset: .1em;
>     }
> }

感谢回复，使用您的代码片段后，实线下划线确实能够正确显示了，请问剩下的虚线下划线应该如何操作？

![Image](https://github.com/user-attachments/assets/ce2b1519-3501-4d70-ade8-29b804573716)

**Comment by mustakshif** [comment]
用这个：

```css
[data-light-theme="Asri"],[data-dark-theme="Asri"] {
    body {
        text-underline-offset: .1em;
    }

    .protyle-wysiwyg :is([data-node-id] span[data-type~=block-ref]:not(.av__celltext), [data-node-id] span[data-type~=file-annotation-ref])[data-subtype=d] {
        text-underline-offset: inherit;
    }
}
```
