### ISSUE TITLE
保持标题的小提示一直显示以便更好地阅读

### ISSUE THREAD

**Issue by aCoo4ie** [mustakshif/Asri#159]
- ## 描述:

![Image](https://github.com/user-attachments/assets/e3f9a597-0387-4616-829e-6fca020f85e8)

在上图中，标题上的小提示显示时间过短，导致在阅读时难以清晰区分序号属于哪个层级。

是否可以将小提示一直显示，方便用户阅读？或者，是否可以自定义小提示一直显示？

- ## 复现步骤：

1. 打开带标题的文档。

2. 将鼠标悬停在标题上。

3. 注意小提示很快消失。

- **预期行为：** 小提示应该一直保持可见，帮助用户理解命令属于哪个层级。

- **实际行为：** 小提示消失得太快，无法清晰显示输入哪个层级，导致用户难以跟上命令与其对应的层级。

**Comment by mustakshif** [comment]
小提示是指块标吧，这个块标每个文档仅有一个，只在鼠标悬停在块上时会在相应的块旁边出现，所以没法保持一直显示。

如果你想要的是标题层级指示，可以使用 Savor 主题的相关代码，放到你的自定义 CSS 代码片段中：

```css
.protyle-wysiwyg {
    .h1, .h2, .h3, .h4, .h5, .h6 {
        & > [spellcheck]:not(:empty) {
            display: inline-block;
            position: relative;
        }
    }
    
    .h1 > [spellcheck]:not(:empty){ padding-right: 1em;background: var(--h1-r-graphic);background-position: right center;background-repeat: no-repeat;}
    .h2 > [spellcheck]:not(:empty){ padding-right: 1.2em;background: var(--h2-r-graphic);background-position: right center;background-repeat: no-repeat;}
    .h3 > [spellcheck]:not(:empty){ padding-right: 1.2em;background: var(--h3-r-graphic);background-position: right center;background-repeat: no-repeat;}
    .h4 > [spellcheck]:not(:empty){ padding-right: 1.3em;background: var(--h4-r-graphic);background-position: right center;background-repeat: no-repeat;}
    .h5 > [spellcheck]:not(:empty){ padding-right: 1.4em;background: var(--h5-r-graphic);background-position: right center;background-repeat: no-repeat;}
    .h6 > [spellcheck]:not(:empty){ padding-right: 1.6em;background: var(--h6-r-graphic);background-position: right center;background-repeat: no-repeat;}
}

:root{

    /* 标题符号 */
    --h1-r-graphic: url("data:image/svg+xml;utf8,<svg fill='rgba(235, 131, 131, 0.4)' height='24' viewBox='0 0 32 32' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M4.8 29.714v0c-1.371 0-2.514-1.143-2.514-2.514v0c0-1.371 1.143-2.514 2.514-2.514v0c1.371 0 2.514 1.143 2.514 2.514v0c0.114 1.371-1.029 2.514-2.514 2.514z'/></svg>") no-repeat  center;
	--h2-r-graphic: url("data:image/svg+xml;utf8,<svg fill='rgba(174, 154, 203, 0.5)' height='24' viewBox='0 0 32 32' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M11.429 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM4.571 18.286c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286z'/></svg>") no-repeat  center;
	--h3-r-graphic: url("data:image/svg+xml;utf8,<svg fill='rgba(125, 181, 205, 0.5)' height='24' viewBox='0 0 32 32' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M4.571 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM4.571 18.286c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286z'/></svg>") no-repeat  center;
	--h4-r-graphic: url("data:image/svg+xml;utf8,<svg fill='rgba(113, 167, 150, 0.5)' height='24' viewBox='0 0 32 32' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M4.571 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM4.571 18.286c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 22.857c1.257 0 2.286-1.029 2.286-2.286s-1.029-2.286-2.286-2.286-2.286 1.029-2.286 2.286 1.029 2.286 2.286 2.286z'/></svg>") no-repeat  center;
	--h5-r-graphic: url("data:image/svg+xml;utf8,<svg fill='rgba(220, 191, 97, 0.5)' height='24' viewBox='0 0 32 32' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M4.571 18.286c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 22.857c1.257 0 2.286-1.029 2.286-2.286s-1.029-2.286-2.286-2.286-2.286 1.029-2.286 2.286 1.029 2.286 2.286 2.286zM4.571 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM4.571 11.429c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286z'/></svg>") no-repeat  center;
	--h6-r-graphic: url("data:image/svg+xml;utf8,<svg fill='rgba(221, 163, 106, 0.5)' height='24' viewBox='0 0 32 32' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M4.571 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM4.571 18.286c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM4.571 11.429c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 18.286c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 25.143c-1.257 0-2.286 1.029-2.286 2.286s1.029 2.286 2.286 2.286 2.286-1.029 2.286-2.286-1.029-2.286-2.286-2.286zM11.429 16c1.257 0 2.286-1.029 2.286-2.286s-1.029-2.286-2.286-2.286-2.286 1.029-2.286 2.286 1.029 2.286 2.286 2.286z'/></svg>") no-repeat  center;
}
```

**Comment by aCoo4ie** [comment]
你好，感谢帮助。在此基础上我又修改了上面的代码，使用修改后的css代码，最终显示为下图。

<img width="996" alt="Image" src="https://github.com/user-attachments/assets/26dfe63e-6b98-4812-b881-da418347cdd3" />

```css
.protyle-wysiwyg {
    .h1, .h2, .h3, .h4, .h5, .h6 {
        & > [spellcheck]:not(:empty) {
            display: inline-block;
            position: relative;
        }
    }
    
    .h1 > [spellcheck]:not(:empty){ padding-right: 1.3em; background: var(--h1-r-graphic); background-position: right center; background-repeat: no-repeat; background-size: auto 70%; }
    .h2 > [spellcheck]:not(:empty){ padding-right: 1.3em; background: var(--h2-r-graphic); background-position: right center; background-repeat: no-repeat; background-size: auto 70%; }
    .h3 > [spellcheck]:not(:empty){ padding-right: 1.3em; background: var(--h3-r-graphic); background-position: right center; background-repeat: no-repeat; background-size: auto 70%; }
    .h4 > [spellcheck]:not(:empty){ padding-right: 1.3em; background: var(--h4-r-graphic); background-position: right center; background-repeat: no-repeat; background-size: auto 70%; }
    .h5 > [spellcheck]:not(:empty){ padding-right: 1.3em; background: var(--h5-r-graphic); background-position: right center; background-repeat: no-repeat; background-size: auto 70%; }
    .h6 > [spellcheck]:not(:empty){ padding-right: 1.3em; background: var(--h6-r-graphic); background-position: right center; background-repeat: no-repeat; background-size: auto 70%; }
}

:root {
    --h1-r-graphic: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' height='32' width='32' viewBox='0 0 24 24'><defs><linearGradient id='grad1' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' style='stop-color:rgba(25,118,210,0.85)'/><stop offset='100%' style='stop-color:rgba(21,101,192,0.75)'/></linearGradient></defs><rect filter='url(%23shadow)' x='4' y='3' width='16' height='18' rx='3' ry='3' fill='url(%23grad1)'/><filter id='shadow'><feDropShadow dx='0' dy='1' stdDeviation='0.5' flood-opacity='0.3'/></filter></svg>") no-repeat center;

    --h2-r-graphic: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' height='32' width='32' viewBox='0 0 24 24'><defs><linearGradient id='grad2' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' style='stop-color:rgba(33,150,243,0.85)'/><stop offset='100%' style='stop-color:rgba(30,136,229,0.75)'/></linearGradient></defs><rect filter='url(%23shadow)' x='4' y='3' width='16' height='8' rx='2' ry='2' fill='url(%23grad2)'/><rect filter='url(%23shadow)' x='4' y='13' width='16' height='8' rx='2' ry='2' fill='url(%23grad2)'/><filter id='shadow'><feDropShadow dx='0' dy='1' stdDeviation='0.4' flood-opacity='0.25'/></filter></svg>") no-repeat center;

    --h3-r-graphic: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' height='32' width='32' viewBox='0 0 24 24'><defs><linearGradient id='grad3' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' style='stop-color:rgba(66,165,245,0.85)'/><stop offset='100%' style='stop-color:rgba(41,121,255,0.75)'/></linearGradient></defs><rect filter='url(%23shadow)' x='4' y='3' width='16' height='5.5' rx='1.5' ry='1.5' fill='url(%23grad3)'/><rect filter='url(%23shadow)' x='4' y='9.5' width='16' height='5.5' rx='1.5' ry='1.5' fill='url(%23grad3)'/><rect filter='url(%23shadow)' x='4' y='16' width='16' height='5.5' rx='1.5' ry='1.5' fill='url(%23grad3)'/><filter id='shadow'><feDropShadow dx='0' dy='1' stdDeviation='0.3' flood-opacity='0.2'/></filter></svg>") no-repeat center;

    --h4-r-graphic: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' height='32' width='32' viewBox='0 0 24 24'><defs><linearGradient id='grad4' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' style='stop-color:rgba(79,195,247,0.85)'/><stop offset='100%' style='stop-color:rgba(41,182,246,0.75)'/></linearGradient></defs><rect filter='url(%23shadow)' x='4' y='3' width='7.2' height='8' rx='1.5' ry='1.5' fill='url(%23grad4)'/><rect filter='url(%23shadow)' x='12.8' y='3' width='7.2' height='8' rx='1.5' ry='1.5' fill='url(%23grad4)'/><rect filter='url(%23shadow)' x='4' y='13' width='7.2' height='8' rx='1.5' ry='1.5' fill='url(%23grad4)'/><rect filter='url(%23shadow)' x='12.8' y='13' width='7.2' height='8' rx='1.5' ry='1.5' fill='url(%23grad4)'/><filter id='shadow'><feDropShadow dx='0' dy='1' stdDeviation='0.3' flood-opacity='0.2'/></filter></svg>") no-repeat center;

    --h5-r-graphic: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' height='32' width='32' viewBox='0 0 24 24'><defs><linearGradient id='grad5' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' style='stop-color:rgba(0,188,212,0.85)'/><stop offset='100%' style='stop-color:rgba(0,172,193,0.75)'/></linearGradient></defs><rect filter='url(%23shadow)' x='4' y='3' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad5)'/><rect filter='url(%23shadow)' x='12.8' y='3' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad5)'/><rect filter='url(%23shadow)' x='4' y='9.4' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad5)'/><rect filter='url(%23shadow)' x='12.8' y='9.4' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad5)'/><rect filter='url(%23shadow)' x='4' y='15.8' width='16' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad5)'/><filter id='shadow'><feDropShadow dx='0' dy='1' stdDeviation='0.3' flood-opacity='0.2'/></filter></svg>") no-repeat center;

    --h6-r-graphic: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' height='32' width='32' viewBox='0 0 24 24'><defs><linearGradient id='grad6' x1='0%' y1='0%' x2='100%' y2='100%'><stop offset='0%' style='stop-color:rgba(77,208,225,0.85)'/><stop offset='100%' style='stop-color:rgba(38,198,218,0.75)'/></linearGradient></defs><rect filter='url(%23shadow)' x='4' y='3' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad6)'/><rect filter='url(%23shadow)' x='12.8' y='3' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad6)'/><rect filter='url(%23shadow)' x='4' y='9.4' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad6)'/><rect filter='url(%23shadow)' x='12.8' y='9.4' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad6)'/><rect filter='url(%23shadow)' x='4' y='15.8' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad6)'/><rect filter='url(%23shadow)' x='12.8' y='15.8' width='7.2' height='5.2' rx='1.5' ry='1.5' fill='url(%23grad6)'/><filter id='shadow'><feDropShadow dx='0' dy='1' stdDeviation='0.3' flood-opacity='0.2'/></filter></svg>") no-repeat center;
}
```
