### ISSUE TITLE
添加H1-6标题预制外观

### ISSUE THREAD

**Issue by seanfy** [mustakshif/Asri#160]
感谢做出了这么漂亮的主题，用了这个终于不折腾其他主题了！

我有个需求，希望能够添加H1-6标题的预制外观，只靠文字大小的区别其实挺不明显的。能否麻烦大佬预制几套标题的外观方案可以选择一下？

可以是颜色和文字样式，也可以是和一些其他主题中那样给不同级别标题加上一个尾巴标识符，主要是功能性的区分一下各个标题。

（个人没有什么能力，用了CSS也折腾不出来好看的效果，所以想大佬预制1，2种，简单的选择一下就好了 :) ）

谢谢！

**Comment by mustakshif** [comment]
感谢喜欢～

颜色区分应该可以解决这个问题。以下是参考代码，可以根据自己的喜好调整参数：

```css

[data-light-theme=Asri],
[data-dark-theme=Asri] {

  @supports (color: oklch(from #00f l clamp(0, c, 0.2) calc(h + 0))) {
    #layouts {
      --heading-clr-primary-base: var(--b3-theme-primary);      /* 起始颜色，这里是主题色，也可以自定义其他颜色值 */
      --hchs: 30;      /*  颜色偏移值，数值越大层级颜色差异越大，建议取值 0-60 */
    }

    :is(.h1, h1) {
      --heading-clr-primary: oklch(from var(--heading-clr-primary-base) l clamp(0, c, .2) calc(h + var(--hchs) * 0));
    }

    :is(.h2, h2) {
      --heading-clr-primary: oklch(from var(--heading-clr-primary-base) l clamp(0, c, .2) calc(h + var(--hchs) * 1));
    }

    :is(.h3, h3) {
      --heading-clr-primary: oklch(from var(--heading-clr-primary-base) l clamp(0, c, .2) calc(h + var(--hchs) * 2));
    }

    :is(.h4, h4) {
      --heading-clr-primary: oklch(from var(--heading-clr-primary-base) l clamp(0, c, .2) calc(h + var(--hchs) * 3));
    }

    :is(.h5, h5) {
      --heading-clr-primary: oklch(from var(--heading-clr-primary-base) l clamp(0, c, .2) calc(h + var(--hchs) * 4));
    }

    :is(.h6, h6) {
      --heading-clr-primary: oklch(from var(--heading-clr-primary-base) l clamp(0, c, .2) calc(h + var(--hchs) * 5));
    }

    :is(.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6) {
      color: var(--heading-clr-primary);
    }
  }
}
```
参考效果：
<img width="360" alt="Image" src="https://github.com/user-attachments/assets/6d5fa26d-192e-4b69-a65e-a954b0c19ebe" />

---

另外也可参考 savor 主题的方案：

https://github.com/mustakshif/Asri/issues/159#issuecomment-2760136648
