### ISSUE TITLE
页签切换有卡顿感

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#171]
对比默认主题，感觉页签切换的速度有点慢，怀疑是页面切换时候的淡入淡出动画比较影响性能，以及页签按下的回弹效果也可能有点卡，有没办法通过css关闭页面加载和页签动画？

**Comment by mustakshif** [comment]
是最近出现的问题吗？理论上这些动效不会造成太大影响，可能是其他样式导致的，我需要再测试一下。

关闭动画可以用这个片段：

```css
[data-light-theme=Asri], [data-dark-theme=Asri] {
    .layout-tab-bar .item {
        animation: none;
        transition: none;
    }
    .protyle:not(.fn__none) .protyle-content {
        animation: none;
    }
}
```
