### ISSUE TITLE
文档标签页间距缩小

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#46]
大佬，有没办法把文档标签页间距调小，现在感觉有点宽(标签页和顶栏二合一了，感觉更应该节约位置)，我css试了好像找不到是哪个参数调

![image](https://github.com/mustakshif/Asri/assets/63196026/5c2547c1-54b7-41ad-85cc-48bdf10197bf)

**Comment by mustakshif** [comment]
```css
.layout-tab-bar .item {
  margin-right: 8px;
}
```

调整这个就行
