### ISSUE TITLE
顶栏颜色css修改

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#60]
大佬您好，我用以下代码想把四周工具栏改改颜色，但是改了顶栏的标签页不显示，请教下大佬是哪里错了
```css
:root[data-theme-mode=light]{
#toolbar {
--b3-toolbar-background: rgb(224,232,234) !important;
background-color:  rgb(224,232,234) !important;
}
#dockLeft.dock.dock--vertical{
 background-color: rgb(224,232,234) !important
}
#dockRight.dock.dock--vertical{
 background-color: rgb(224,232,234) !important
}
}
``` 
![image](https://github.com/mustakshif/Asri/assets/63196026/96f498f8-8617-4969-b6d6-cdaddb6b7a9d)

**Comment by mustakshif** [comment]
添加这个

```css
.layout-tab-bar {
    z-index: 3;
}
```

**Comment by 5kyfkr** [comment]
> 添加这个
> 
> ```css
> .layout-tab-bar {
>     z-index: 3;
> }
> ```

感谢大佬，好了

**Comment by 5kyfkr** [comment]
https://github.com/mustakshif/Asri/assets/63196026/56bed39a-1721-4597-a0d6-3e0e9d4d9dc5

大佬再帮忙看看左上角为什么有一小块颜色会切换，我用选择器点选不到

**Comment by mustakshif** [comment]
```css
body:not(.body--mobile, .body--window) .layout__dockl.layout--float::before {
    background-color: rgb(224,232,234);
}
```

**Comment by 5kyfkr** [comment]
> ```css
> body:not(.body--mobile, .body--window) .layout__dockl.layout--float::before {
>     background-color: rgb(224,232,234);
> }
> ```

厉害了我滴神

**Comment by 5kyfkr** [comment]
```css
:root[data-theme-mode=light] {
--b3-theme-background: rgb(241,246,246) !important;
--b3-theme-surface: rgb(232, 239, 240);
--b3-toolbar-blur-background: rgb(47,54,61);
}
``` 
大佬，还有个问题是手机端上用--b3-theme-background这个改不了编辑器的背景颜色，客户端一直是255,255,255的纯白，但是在深色模式下又可以，是手机端的日间模式背景颜色设置哪不一样嘛

**Comment by mustakshif** [comment]
```css
:root[data-theme-mode=light] .body--mobile {
    background-color: rgb(241,246,246);
}
```

之前为了修复 #39 强制将亮色模式背景色转为 hex 白色了。你可以试试看 rgb 颜色会不会有问题，如果有就用 hex 颜色
