### ISSUE TITLE
移动端数据库全宽显示

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#63]
关联issues：https://github.com/siyuan-note/siyuan/issues/11331
如题，目前全宽显示afwd在移动端似乎没效果，看看能不能加上？主要需要数据库的全宽显示，目前我都是文档属性增加afwd+db用。
另外大佬有没办法用css改手机端页边距，这个也挺需要

**Comment by mustakshif** [comment]
统一在这里回了哈。

移动端全宽显示下个版本更新；

---

移动端可以调整页边距，从下面选一个选择器，调整 padding 即可：
```css
/* 调整对所有主题生效 */
#editor .protyle-wysiwyg {}

/* 仅调整 Asri 主题下页边距 */
.body--mobile .protyle-wysiwyg {}
```
注意给 padding 的内容加上 `!important`。

如果你调整了页边距，建议添加以下 css 保持全宽显示正确显示：

```css
.protyle-wysiwyg {
    --protyle-spacing-compatible: var(--protyle-spacing, 24px);
}
```

将其中的 `24px` 换成调整后的左或右边距的值（左右边距请尽量保持一致）。

**Comment by mustakshif** [comment]
可以替换最新 theme.css 了

**Comment by mustakshif** [comment]
另外不知你用过 `网页视图` 插件没有，可以在电脑上调出移动端窗口，比较方便调试

**Comment by 5kyfkr** [comment]
> 另外不知你用过 `网页视图` 插件没有，可以在电脑上调出移动端窗口，比较方便调试

学到了，我试试

**Comment by 5kyfkr** [comment]
感谢巨佬，把思源移动端又提升到全新境界了，已经把Asri焊死在我的思源上了
下面这个试着页边距刚合适，右边有滚动条所以要让点位置
```css
#editor .protyle-wysiwyg { 
padding-left: 18px !important;
padding-right: 14px !important;
}

.protyle-wysiwyg {
    --protyle-spacing-compatible: var(--protyle-spacing, 18px);
}
```
