### ISSUE TITLE
手机端状态栏颜色首次进入无法应用背景色css

### ISSUE THREAD

**Issue by 5kyfkr** [mustakshif/Asri#71]
大佬，如下图，手机端用了这个改背景色的css，然后首次进入app的时候顶栏无法应用背景色，但是外观里切换下夜间模式再切回来又可以了，颜色代码也是hex格式，好像是从思源3.0.15最新版开始这样的

```css
:root[data-theme-mode=light] .body--mobile {
--b3-theme-background: #f2f3f7 !important;
}

``` 

![Screenshot_20240524_080239](https://github.com/mustakshif/Asri/assets/63196026/bbd5fb59-8201-40db-8123-798bc675b47a)

**Comment by mustakshif** [comment]
> ```css
> :root[data-theme-mode=light] .body--mobile {
> --b3-theme-background: #f2f3f7 !important;
> }
> ```

是不是自定义代码加载出了问题。我这里把这段代码写入 theme.css 后可以直接看到效果，不用切换亮暗模式

**Comment by 5kyfkr** [comment]
> > ```css
> > :root[data-theme-mode=light] .body--mobile {
> > --b3-theme-background: #f2f3f7 !important;
> > }
> > ```
> 
> 是不是自定义代码加载出了问题。我这里把这段代码写入 theme.css 后可以直接看到效果，不用切换亮暗模式

挂载到代码片段也能直接看到嘛？

**Comment by mustakshif** [comment]
> 挂载到代码片段也能直接看到嘛？

你是通过电脑上加入代码片段同步到手机上的吗，我是直接修改手机主题目录中的css文件来的

**Comment by 5kyfkr** [comment]
感

> > 挂载到代码片段也能直接看到嘛？
> 
> 你是通过电脑上加入代码片段同步到手机上的吗，我是直接修改手机主题目录中的css文件来的

是滴，我是电脑上代码片段同步到手机上，也可以手机上打开伺服，然后进手机浏览器127.0.0.1:6806进去网页端改代码片段

**Comment by 5kyfkr** [comment]
感觉有点像用rgb()情况的状况，只不过rgb()的时候切换外观也不会有效果

**Comment by mustakshif** [comment]
我通过手机浏览器改代码片段也是进入应用就能正确显示的

**Comment by 5kyfkr** [comment]
> 我通过手机浏览器改代码片段也是进入应用就能正确显示的

辣么神奇，那就不管了，白色界面我还是用原生颜色吧

**Comment by 5kyfkr** [comment]
大佬请教个问题，我想在移动端实现下图加粗后文本的颜色与主字体不同，但是用以下面的代码没效果，但是桌面端有效果，是移动端和桌面端对应的类不同嘛？
![image](https://github.com/mustakshif/Asri/assets/63196026/4541bfd5-2d21-48a6-8afd-1206b0a7f654)

```css
:root[data-theme-mode=dark] {
--b3-protyle-inline-strong-color: #e8eaed !important;
.b3-typography strong, .b3-typography span[data-type~=strong], .protyle-wysiwyg strong, .protyle-wysiwyg span[data-type~=strong] {
    color: var(--b3-protyle-inline-strong-color);
}
```

**Comment by mustakshif** [comment]
> ```css
> :root[data-theme-mode=dark] {
> --b3-protyle-inline-strong-color: #e8eaed !important;
> .b3-typography strong, .b3-typography span[data-type~=strong], .protyle-wysiwyg strong, .protyle-wysiwyg span[data-type~=strong] {
>     color: var(--b3-protyle-inline-strong-color);
> }
> ```

最后少了一个}，可能手机上没法解析？

```css
:root[data-theme-mode=dark] {
    --b3-protyle-inline-strong-color: #e8eaed !important;

    .b3-typography strong,
    .b3-typography span[data-type~=strong],
    .protyle-wysiwyg strong,
    .protyle-wysiwyg span[data-type~=strong] {
        color: var(--b3-protyle-inline-strong-color);
    }
}
```
