### ISSUE TITLE
引述字体颜色变谈可以用css取消吗？

### ISSUE THREAD

**Issue by AvoidantPerDis** [mustakshif/Asri#72]
![image](https://github.com/mustakshif/Asri/assets/154863885/f8792c3d-de45-46e0-bb29-b1020942c164)

**Comment by AvoidantPerDis** [comment]
另外就是当前页签字数能否用css限制啊，我有的PDF标题很长，但是附件不好改名

**Comment by mustakshif** [comment]
引述块字体颜色是跟随默认主题样式的，不过也可以调整：

```css
.b3-typography blockquote, .b3-typography .bq, .protyle-wysiwyg blockquote, .protyle-wysiwyg .bq {
    color: var(--b3-theme-on-background);
}
```

> 另外就是当前页签字数能否用css限制啊，我有的PDF标题很长，但是附件不好改名

```css
.layout-tab-bar .item--focus {
    max-width: 186px;
}
```
