### ISSUE TITLE
界面优化：两处引用链接样式希望更加直观

### ISSUE THREAD

**Issue by luluciamk** [mustakshif/Asri#96]
大大，现在数据库的引用链接，必须鼠标拖动到标题上面才能显示。
希望可以变更，更加直观在标题上就显示出“引用链接”
参考：这是原图
![image](https://github.com/user-attachments/assets/8e4caa85-82b1-45ac-b8ff-cfd88c41bd34)
修改成这种类似的，颜色不如就和主题自带的双链颜色保持一致
![image](https://github.com/user-attachments/assets/cc62317b-8773-42b4-bbb0-44506c765004)

另，目前引用链接的下划线可以更粗一点吗？现在有点不易分辨
![image](https://github.com/user-attachments/assets/ff9d5a9d-008c-416a-a267-a421c532087f)
这个是局部截图，特意放大了，所以可能看起来还不错，但实际这个文本在编辑器里显示时很小，连带着这个链接下划线更细，在黑色背景下都是如此，如果加了壁纸，这个就更加不容易看清楚。

**Comment by mustakshif** [comment]
感谢反馈。

数据库主键引用样式下个版本更新。

动态锚文本的块引链接下划线样式下个版本会稍微加粗一点。如果觉得还是太细，可以使用自定义CSS片段：

```css
[data-light-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=block-ref]:not(.av__celltext)[data-subtype=d],
[data-dark-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=block-ref]:not(.av__celltext)[data-subtype=d] {
    text-decoration-thickness: .2em;
}
```
