### ISSUE TITLE
界面优化：悬浮框里的引用链接可以增加背景色吗？

### ISSUE THREAD

**Issue by luluciamk** [mustakshif/Asri#97]
目前正向引链是当鼠标拖动到上面时，引链会出现背景色，提示注意
但是，在引用悬浮框里这种场景下，引用块会同时出现在多个悬浮框中，这种时候感觉也挺需要“注意”，所以希望增加背景色用来更加突出。
如图：
现在Asri是这样的
![image](https://github.com/user-attachments/assets/1b8b24de-6caa-4977-bdac-94fcdd43e74c)
如果能改成积读这种，感觉会更加显眼清晰一点，让人更集中注意力。
![image](https://github.com/user-attachments/assets/e69f3e7b-ac55-4b96-a206-174956816a22)
（不常用积读这个主题，原因是积读的蒙版蓝不是很喜欢，asri的蓝色比较清爽）

另，可否请大大帮忙写一个修改网页链接的css？
我自定义的外链样式目前在Asri主题下失效无法使用（加了important也没用）

即，asri下，网页链接是在link下方划一道实线（我个人感觉这个与原编辑器的下划线会重合——尤其是用“外观”修改字体颜色后，这个下划线也会一同变色，而下划线则是我经常用的）

我更喜欢的link样式，则是直接用颜色字体来呈现。
这种方案下，颜色字体更醒目，因为加了logo，也不会轻易和普通文本弄混。
具体来说，就是大致原生样式的这种样式类型
如图
 
![image](https://github.com/user-attachments/assets/aa0e8387-ecae-4d61-98f9-17c88b38e2e9)

**Comment by mustakshif** [comment]
块引用样式：
```css
[data-light-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=block-ref]:not(.av__celltext), 
[data-light-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=file-annotation-ref], 
[data-dark-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=block-ref]:not(.av__celltext), 
[data-dark-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=file-annotation-ref] {
    background-size: 100%;
}
```


超链接样式：
```css
[data-light-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=a], [data-light-theme=Asri] .protyle-wysiwyg a, 
[data-dark-theme=Asri] .protyle-wysiwyg [data-node-id] span[data-type~=a], [data-dark-theme=Asri] .protyle-wysiwyg a {
    color: var(--b3-theme-primary);
    text-decoration: none;
}
```
